---
- hosts: all
  name: jenkins-playbook
  remote_user: amr92621
  become: true
  gather_facts: false
  tasks:
    - name: Create master directory
      ansible.builtin.file:
        state: directory
        path: /home/amr92621/master
    - name: Create slave directory
      ansible.builtin.file:
        state: directory
        path: /home/amr92621/slave
    - name: Copy master files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/amr92621/master
        mode: "777"
      with_items:
        - ~/Documents/Final-Project/terraform/jenkins-deployment/master/deploy-master.yaml
        - ~/Documents/Final-Project/terraform/jenkins-deployment/master/service-master.yaml
    - name: Copy slave files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/amr92621/slave
        mode: "777"
      with_items:
        - ~/Documents/Final-Project/terraform/jenkins-deployment/slave/deploy-slave.yaml
        - ~/Documents/Final-Project/terraform/jenkins-deployment/slave/service-slave.yaml